//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void lv_rt_log(lv_log_level_t level, const char *buf); \
	uint32_t my_tick(void); \
	void my_touchpad_read(lv_indev_t *indev, lv_indev_data_t *data); \
	void setup(); \
	void loop(); \

